export const STELLA_WORDS = [
  'Bosque Encantado',
  'Universo',
  'Sueño',
  'Memoria',
  'Viaje',
  'Silencio',
  'Tormenta',
  'Destino',
  'Reflejo',
  'Secreto',
  'Laberinto',
  'Metamorfosis',
  'Horizonte',
  'Espejismo',
  'Melodía',
  'Fantasía',
  'Frágil',
  'Eclipse',
  'Raíces',
  'Fuego',
  'Marea',
  'Susurro',
  'Máscara',
  'Anhelo',
  'Equilibrio',
  'Ritual',
  'Infinito',
  'Invierno',
  'Ascenso',
  'Aurora',

  'Estrella Perdida',
  'Jardín Lunar',
  'Niebla',
  'Cristal',
  'Ceniza',
  'Bruma',
  'Eco',
  'Abismo',
  'Constelación',
  'Nostalgia',
  'Alba',
  'Crepúsculo',
  'Luz',
  'Sombra',
  'Círculo',
  'Oráculo',
  'Profecía',
  'Portal',
  'Alquimia',
  'Hechizo',
  'Sortilegio',
  'Encanto',
  'Leyenda',
  'Misterio',
  'Caverna',
  'Templo',
  'Santuario',
  'Ruinas',
  'Corona',
  'Trono',
  'Reino',
  'Exilio',
  'Regreso',
  'Promesa',
  'Juramento',
  'Herida',
  'Cicatriz',
  'Resplandor',
  'Centella',
  'Relámpago',
  'Trueno',
  'Llama',
  'Hoguera',
  'Brasas',
  'Océano',
  'Olas',
  'Corriente',
  'Isla',
  'Náufrago',
  'Faro',
  'Puerto',
  'Barco',
  'Vela',
  'Mapa',
  'Brújula',
  'Sendero',
  'Camino',
  'Montaña',
  'Cumbre',
  'Valle',
  'Río',
  'Cascada',
  'Lago',
  'Manantial',
  'Desierto',
  'Duna',
  'Oasis',
  'Selva',
  'Pradera',
  'Flor',
  'Pétalo',
  'Espina',
  'Rosa',
  'Lirio',
  'Hiedra',
  'Semilla',
  'Árbol Ancestral',
  'Hoja',
  'Viento',
  'Vendaval',
  'Aliento',
  'Lluvia',
  'Rocío',
  'Escarcha',
  'Nieve',
  'Hielo',
  'Solsticio',
  'Equinoccio',
  'Verano',
  'Primavera',
  'Otoño',
  'Medianoche',
  'Amanecer',
  'Atardecer',
  'Luna',
  'Luna Nueva',
  'Luna Llena',
  'Luz Estelar',
  'Polvo de Estrellas',
  'Vía Láctea',
  'Galaxia',
  'Nebulosa',
  'Cometa',
  'Meteorito',
  'Astro',
  'Órbita',
  'Gravedad',
  'Vacío',
  'Eternidad',
  'Tiempo',
  'Instante',
  'Recuerdo',
  'Olvido',
  'Deseo',
  'Esperanza',
  'Melancolía',
  'Alegría',
  'Ternura',
  'Valentía',
  'Miedo',
  'Duda',
  'Fe',
  'Calma',
  'Caos',
  'Armonía',
  'Contraste',
  'Dualidad',
  'Renacer',
  'Caída',
  'Vuelo',
  'Alas',
  'Pluma',
  'Ave Fénix',
  'Dragón',
  'Sirena',
  'Unicornio',
  'Grifo',
  'Quimera',
  'Esfinge',
  'Titán',
  'Ninfa',
  'Hada',
  'Elfo',
  'Guardián',
  'Viajero',
  'Soñador',
  'Errante',
  'Forastero',
  'Sombra Antigua',
  'Voz Interior',
  'Canto',
  'Canción',
  'Arpa',
  'Piano',
  'Danza',
  'Más Allá',
  'Umbral',
  'Puerta Secreta',
  'Llave',
  'Cofre',
  'Tesoro',
  'Pergamino',
  'Libro Prohibido',
  'Tinta',
  'Papel',
  'Escritura',
  'Símbolo',
  'Runas',
  'Glifo',
  'Espejo',
  'Prisma',
  'Diamante',
  'Zafiro',
  'Rubí',
  'Esmeralda',
  'Ópalo',
  'Amatista',
  'Obsidiana',
  'Perla',
  'Oro',
  'Plata',
  'Cobre',
  'Reloj',
  'Arena',
  'Campana',
  'Latido',
  'Pulso',
  'Respirar',
  'Alma',
  'Espíritu',
  'Destino Roto',
  'Pacto',
  'Sacrificio',
  'Milagro',
  'Revelación',
  'Verdad',
  'Mentira',
  'Ilusión',
  'Visión',
  'Presagio',
  'Señal',
  'Destino Oculto',
  'Camino Estelar',
  'Torre',
  'Muralla',
  'Castillo',
  'Puente',
  'Escalera',
  'Ascensión',
  'Caos Celeste',
  'Travesía',
  'Horizonte Azul',
  'Jardín Secreto',
  'Ciudad Dormida',
  'Palacio de Cristal',
  'Mar de Nubes',
  'Río de Luz',
  'Bosque de Sombras',
  'Valle de Ecos',
  'Cielo Infinito',
  'Llama Eterna',
  'Corazón Salvaje',
  'Corona Lunar',
  'Trono Vacío',
  'Reloj de Arena',
  'Canción Antigua',
  'Sueño Dorado',
  'Memoria Perdida',
  'Silencio Profundo',
  'Eclipse Total',
  'Aurora Boreal',
  'Tormenta Solar',
  'Espejo Roto',
  'Puerta del Alba',
  'Noche Eterna',
  'Luz Prohibida',
  'Sombra Errante',
  'Alma Gemela',
  'Fuego Sagrado',
  'Océano Interior',
  'Susurro del Viento',
  'Danza de Estrellas',
  'Piel de Luna',
  'Lágrima de Cristal',
  'Canto del Abismo',
  'Semilla del Tiempo',
  'Flor del Destino',
  'Raíz Celeste',
  'Marea Lunar',
  'Invierno Azul',
  'Primavera Eterna',
  'Último Refugio',
  'Primer Latido',
  'Última Luz',
  'Nuevo Amanecer',
] as const;
